version: '3.8'

services:
  frontend:
    build:
      context: ./FRONTEND
    ports:
      - "3000:80"
    depends_on:
      - backend
    env_file:
      - ./FRONTEND/.env

  backend:
    build:
      context: ./BACKEND
    ports:
      - "4000:4000"
      